In [3]:
%matplotlib inline
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import pickle
from sklearn import neighbors
from sklearn import datasets
from sklearn import metrics
from math import exp
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import scale
from sklearn import preprocessing
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import seaborn as sns

In [4]:
df = pd.read_csv('creditcard.csv')

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 284807 entries, 0 to 284806
Data columns (total 31 columns):
 #   Column  Non-Null Count   Dtype  
---  ------  --------------   -----  
 0   Time    284807 non-null  float64
 1   V1      284807 non-null  float64
 2   V2      284807 non-null  float64
 3   V3      284807 non-null  float64
 4   V4      284807 non-null  float64
 5   V5      284807 non-null  float64
 6   V6      284807 non-null  float64
 7   V7      284807 non-null  float64
 8   V8      284807 non-null  float64
 9   V9      284807 non-null  float64
 10  V10     284807 non-null  float64
 11  V11     284807 non-null  float64
 12  V12     284807 non-null  float64
 13  V13     284807 non-null  float64
 14  V14     284807 non-null  float64
 15  V15     284807 non-null  float64
 16  V16     284807 non-null  float64
 17  V17     284807 non-null  float64
 18  V18     284807 non-null  float64
 19  V19     284807 non-null  float64
 20  V20     284807 non-null  float64
 21  V21     28

In [6]:
df.head()

Time        V1        V2        V3        V4        V5        V6        V7  \
0   0.0 -1.359807 -0.072781  2.536347  1.378155 -0.338321  0.462388  0.239599   
1   0.0  1.191857  0.266151  0.166480  0.448154  0.060018 -0.082361 -0.078803   
2   1.0 -1.358354 -1.340163  1.773209  0.379780 -0.503198  1.800499  0.791461   
3   1.0 -0.966272 -0.185226  1.792993 -0.863291 -0.010309  1.247203  0.237609   
4   2.0 -1.158233  0.877737  1.548718  0.403034 -0.407193  0.095921  0.592941   

         V8        V9  ...       V21       V22       V23       V24       V25  \
0  0.098698  0.363787  ... -0.018307  0.277838 -0.110474  0.066928  0.128539   
1  0.085102 -0.255425  ... -0.225775 -0.638672  0.101288 -0.339846  0.167170   
2  0.247676 -1.514654  ...  0.247998  0.771679  0.909412 -0.689281 -0.327642   
3  0.377436 -1.387024  ... -0.108300  0.005274 -0.190321 -1.175575  0.647376   
4 -0.270533  0.817739  ... -0.009431  0.798278 -0.137458  0.141267 -0.206010   

        V26       V27       V28  Amount  Class  
0 -0.189115  0.133558 -0.021053  149.62      0  
1  0.125895 -0.008983  0.014724    2.69      0  
2 -0.139097 -0.055353 -0.059752  378.66      0  
3 -0.221929  0.062723  0.061458  123.50      0  
4  0.502292  0.219422  0.215153   69.99      0  

[5 rows x 31 columns]

In [7]:
sum(df.duplicated())

1081

In [8]:
df.drop_duplicates(inplace = True)

In [9]:
y = df.Class;
X = df.iloc[:, df.columns != 'Class']

In [10]:
y.head()

0    0
1    0
2    0
3    0
4    0
Name: Class, dtype: int64

In [11]:
y.tail()

284802    0
284803    0
284804    0
284805    0
284806    0
Name: Class, dtype: int64

In [12]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=12, stratify=y)

C00 true negatives, C10 false negatives, C01 false positive,  C11 true positives

In [16]:
# Vary the number of neighbors in the classifier

# This prints the statistics, comparing the result (output of the predictor) with
# the answer (the actual values for those samples)
def classifierStats(label, result, answer):
    print(f'--- {label} Stats ---')
    print(f'classification accuracy: {100*metrics.accuracy_score(result, answer):.2f}%')
    print(f'confusion matrix:\n{metrics.confusion_matrix(result, answer)}')

# Given a dataset (x) and the actual outputs (y), build a KNN with a given number
# of nearest neighbors (num_neigh), then print the statistics
def classifyWithNeighbors(x, y, num_neigh):
    knn = neighbors.KNeighborsClassifier(n_neighbors = num_neigh)
# Train the classifier
    knn.fit(x, y)
# Compute the prediction according to the model
    yhat = knn.predict(X_test)
    classifierStats(num_neigh, y_test,yhat)
    

In [18]:
for i in range(1, 10, 2):
    classifyWithNeighbors(X_train, y_train, i)

--- 1 Stats ---
classification accuracy: 99.80%
confusion matrix:
[[56619    32]
 [   81    14]]
--- 3 Stats ---
classification accuracy: 99.84%
confusion matrix:
[[56651     0]
 [   89     6]]
--- 5 Stats ---
classification accuracy: 99.84%
confusion matrix:
[[56651     0]
 [   93     2]]
--- 7 Stats ---
classification accuracy: 99.83%
confusion matrix:
[[56651     0]
 [   95     0]]
--- 9 Stats ---
classification accuracy: 99.83%
confusion matrix:
[[56651     0]
 [   95     0]]
